file_paths:
    input_calibration_path: example_calibration/diamond_2022_CeO2_pyFAI.poni
    # Input file path for the .poni calibration file
    
    input_path: example_data/
    # Input file path for the diffraction pattern tiff images
    
    input_experiment_list:
    - ""
    # Input experiment list (name of input folders)
    
    output_path: example_analysis/
    # Output path for intensity-time plots
    
    output_experiment_list:
    - ""
    # Output experiment list (name of output folders)
    
user_inputs: 
    lattice_planes:
    - "10-10"
    - "0002"
    - "110"
    - "10-11"
    - "10-12"
    - "200"
    # list of the hkil or hkl indices of the lattice plane peak labels.

    two_theta_min:
    - [3.05, 3.30, 3.40, 3.48, 4.52, 4.76]
    # list of the minimum two theta bounds for each lattice plane peak and each experiment

    two_theta_max:
    - [3.13, 3.35, 3.46, 3.58, 4.61, 4.92] 
    # list of the maximum two theta bounds for each lattice plane peak and each experiment

    v_max:
    - [20000, 40000, 35000, 110000, 15000, 20000]
    # list of the colormap data range for intensity-time plot for each lattice plane peak

    number_of_points:
    - 10000
    # number of points in two-theta for the integration, 10000 gives best two-theta resolution, but 1000 is faster to run

    number_of_cakes:
    - 360
    # number of azimuthal cakes, 360 gives 1 degree azimuthal resolution

    image_step:
    - 1
    # image step to analyse the data

    acquisition_frequency:
    - 100
    # acquisition frequency of the data collection (in Hz)




